# Pandas

In [1]:
with open("./data/bank-additional-names.txt") as f:
    print(f.read())

﻿Citation Request:
  This dataset is publicly available for research. The details are described in [Moro et al., 2014].
  Please include this citation if you plan to use this database:

  [Moro et al., 2014] S. Moro, P. Cortez and P. Rita. A Data-Driven Approach to Predict the Success of Bank Telemarketing. Decision Support Systems, In press, http://dx.doi.org/10.1016/j.dss.2014.03.001

  Available at: [pdf] http://dx.doi.org/10.1016/j.dss.2014.03.001
                [bib] http://www3.dsi.uminho.pt/pcortez/bib/2014-dss.txt

1. Title: Bank Marketing (with social/economic context)

2. Sources
   Created by: Sérgio Moro (ISCTE-IUL), Paulo Cortez (Univ. Minho) and Paulo Rita (ISCTE-IUL) @ 2014

3. Past Usage:

  The full dataset (bank-additional-full.csv) was described and analyzed in:

  S. Moro, P. Cortez and P. Rita. A Data-Driven Approach to Predict the Success of Bank Telemarketing. Decision Support Systems (2014), doi:10.1016/j.dss.2014.03.001.

4. Relevant Information:

   This dataset is based on "Bank Marketing" UCI dataset (please check the description at: http://archive.ics.uci.edu/ml/datasets/Bank+Marketing).
   The data is enriched by the addition of five new social and economic features/attributes (national wide indicators from a ~10M population country), published by the Banco de Portugal and publicly available at: https://www.bportugal.pt/estatisticasweb.
   This dataset is almost identical to the one used in [Moro et al., 2014] (it does not include all attributes due to privacy concerns).
   Using the rminer package and R tool (http://cran.r-project.org/web/packages/rminer/), we found that the addition of the five new social and economic attributes (made available here) lead to substantial improvement in the prediction of a success, even when the duration of the call is not included. Note: the file can be read in R using: d=read.table("bank-additional-full.csv",header=TRUE,sep=";")

   The zip file includes two datasets:
      1) bank-additional-full.csv with all examples, ordered by date (from May 2008 to November 2010).
      2) bank-additional.csv with 10% of the examples (4119), randomly selected from bank-additional-full.csv.
   The smallest dataset is provided to test more computationally demanding machine learning algorithms (e.g., SVM).

   The binary classification goal is to predict if the client will subscribe a bank term deposit (variable y).

5. Number of Instances: 41188 for bank-additional-full.csv

6. Number of Attributes: 20 + output attribute.

7. Attribute information:

   For more information, read [Moro et al., 2014].

   Input variables:
   # bank client data:
   1 - age (numeric)
   2 - job : type of job (categorical: "admin.","blue-collar","entrepreneur","housemaid","management","retired","self-employed","services","student","technician","unemployed","unknown")
   3 - marital : marital status (categorical: "divorced","married","single","unknown"; note: "divorced" means divorced or widowed)
   4 - education (categorical: "basic.4y","basic.6y","basic.9y","high.school","illiterate","professional.course","university.degree","unknown")
   5 - default: has credit in default? (categorical: "no","yes","unknown")
   6 - housing: has housing loan? (categorical: "no","yes","unknown")
   7 - loan: has personal loan? (categorical: "no","yes","unknown")
   # related with the last contact of the current campaign:
   8 - contact: contact communication type (categorical: "cellular","telephone")
   9 - month: last contact month of year (categorical: "jan", "feb", "mar", ..., "nov", "dec")
  10 - day_of_week: last contact day of the week (categorical: "mon","tue","wed","thu","fri")
  11 - duration: last contact duration, in seconds (numeric). Important note:  this attribute highly affects the output target (e.g., if duration=0 then y="no"). Yet, the duration is not known before a call is performed. Also, after the end of the call y is obviously known. Thus, this input should only be included for benchmark purposes and should be discarded if the intention is to have a realistic predictive model.
   # other attributes:
  12 - campaign: number of contacts performed during this campaign and for this client (numeric, includes last contact)
  13 - pdays: number of days that passed by after the client was last contacted from a previous campaign (numeric; 999 means client was not previously contacted)
  14 - previous: number of contacts performed before this campaign and for this client (numeric)
  15 - poutcome: outcome of the previous marketing campaign (categorical: "failure","nonexistent","success")
   # social and economic context attributes
  16 - emp.var.rate: employment variation rate - quarterly indicator (numeric)
  17 - cons.price.idx: consumer price index - monthly indicator (numeric)
  18 - cons.conf.idx: consumer confidence index - monthly indicator (numeric)
  19 - euribor3m: euribor 3 month rate - daily indicator (numeric)
  20 - nr.employed: number of employees - quarterly indicator (numeric)

  Output variable (desired target):
  21 - y - has the client subscribed a term deposit? (binary: "yes","no")

8. Missing Attribute Values: There are several missing values in some categorical attributes, all coded with the "unknown" label. These missing values can be treated as a possible class label or using deletion or imputation techniques.

Q.1.1  
★ pandasで　"./bank-additional.csv" をデータフレームとして開き、dfという名前の変数に格納せよ。

In [2]:
import pandas as pd

Q.1.2  
★ pandasで　"./bank-additional.csv" をデータフレームとして返すget_dfという関数を作成せよ。  
※以降、問題を解く時にdfが変になってしまったら、get_df()で呼び出してdfを初期化すれば良い。

Q.1.3  
★dfの内容をhead,tail,info,describeで確認せよ。

Q.2.1  
★dfの行数と列数はそれぞれいくつか。

Q.3.1  
★ dfの1行目で列名がjobの値を切り出せ。

Q.3.2  
★ dfの1,3行目で列名がjob,educationの値を切り出せ。

Q.3.3  
★ dfの1〜5行目で列名がcampaign,pdaysの値を切り出せ。

Q.3.4  
★dfの1行1列を切り出せ。

Q.3.5  
★dfの2〜4行と1〜3列を切り出せ。

Q.3.6  
★ dfの最終行と最終列の値（データフレームの一番右下）を切り出せ。

Q.3.7.  
★ dfの列名がjobとageの列を切り出せ。

Q.3.8  
★ dfの列名がjobの列をシリーズとして切り出せ。

Q.3.9  
★ dfの列名がjobの列をデータフレームとして切り出せ。

Q.3.10  
★dfのageが20以下の行を切り出せ。

Q.3.11  
★ dfのageが20以下でloanがyesの行を切り出せ。

In [20]:
# ヒント
d1 = pd.DataFrame([1, 2, 3])
d2 = pd.DataFrame([5, 6, 7])
(d1 >= 2) & (d2 <= 6)

       0
0  False
1   True
2  False

Q.4.1  
★ dfに「over_25」という列を追加せよ。追加する列のセルの値は全て「yes」とせよ。

Q.4.2  
★ dfに「over_25」という列を追加せよ。追加する列のセルの値はageが25より大きい時に「yes」、ageが25以下の場合「no」とせよ。

Q.4.3  
★ dfからage列を削除したデータフレームを表示せよ。

Q.4.4  
★★ dfの最終行の下に最終行と同じ内容の行を追加せよ。  
インデックス番号は最終行のインデックス番号より1つ大きくすること。

Q.5.1  
★ dfの「yes」というセルを全て欠損値にせよ。  
ヒント：欠損値はnp.nanで作り出せる

In [26]:
# ヒント
df[df == "yes"]

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,over_25
0,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
2,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
6,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
7,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
10,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
13,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
17,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
18,NaN,NaN,NaN,NaN,NaN,yes,yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
19,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,yes
20,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,yes
22,NaN,NaN,NaN,NaN,NaN,yes,yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
23,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
24,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
25,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,yes
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4090,NaN,NaN,NaN,NaN,NaN,yes,yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4091,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4092,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4093,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4094,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4095,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4096,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4097,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4098,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4099,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4101,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4102,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4103,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4104,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4105,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4106,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4107,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4108,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4111,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4112,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4113,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4114,NaN,NaN,NaN,NaN,NaN,yes,yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4115,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4118,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes
4119,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes

Q.5.2  
★ dfの「yes」というセルを全て欠損値にし、欠損が存在する列名を表示せよ。

Q.5.3  
★ dfの「yes」というセルを全て欠損値にし、欠損が存在するセルを含む行を全て表示せよ。

Q.5.4  
★ dfの「yes」というセルを全て欠損値にし、欠損を含む行を削除したデータフレームを表示せよ。

Q.5.5  
★ dfの「yes」というセルを全て欠損値にし、欠損を含む列を削除したデータフレームを表示せよ。

Q.5.6  
★ dfの「yes」というセルを全て欠損値にし、欠損を含むセルを「unknown」という値に変更したデータフレームを表示せよ。

Q.6.1  
★ dfのjob列の重複行を削除したデータフレームを表示せよ。

Q.7.1  
★ dfのage列の最大値、最小値、平均値を求めよ。

Q.7.2  
★ 列ごとにdfの「unknown」というセルの個数を求めよ。

Q.7.3  
★ dfの「unknown」というセルの総個数を求めよ。

Q.7.4  
★ dfのageが20以上、30未満のセル個数を求めよ。

In [37]:
# ヒント
import numpy as np
np.array([True, True, False]) & np.array([False, True, True])

array([False,  True, False])

Q.8.1  
★ dfのjob列の列名をworkに変更したデータフレームを表示せよ。

Q.8.2  
★ dfのindexを「No.{数字}」に変更せよ。  
例  
0 → No.0  
1 → No.1  
2 → No.2

In [40]:
# ヒント
["No." + str(i) for i in range(5)]

['No.0', 'No.1', 'No.2', 'No.3', 'No.4']

Q.8.3  
★ dfのindexを「No.{数字}」に変更した後、indexをリセットせよ。

Q.9.1    
★ groupbyを用いて、jobごとの最大ageを求めよ。  
ヒント：最初にjob列とage列でデータフレームを切り出した後に処理をすると見やすくなる。

Q.9.2    
★ groupbyを用いて、jobごとmaritalごとの平均ageを求めよ。  
ヒント: 平均はmean()で求められる。

Q.10.1    
★ ピボットせよ。値はage、インデックスはjobとmarital、集計関数は平均を用いよ。  
ヒント：pivot_tableの引数にaggfunc=np.meanを指定する。

Q.11.1    
★ age列をfloat型に変更せよ。

Q.11.2    
★ age列で降順にソートしたデータフレームを表示せよ。

Q.11.3    
★以下のデータフレームを作成せよ。（１行目はヘッダーとして列名を表す。）  
A, B  
1, 2  
3, 4  
5, 6

Q.12.1    
★以下のデータフレームを作成し、day_of_week列でdfとmergeせよ。（１行目はヘッダーとして列名を表す。）  
day_of_week, week_index  
sun,1  
mon,2   
tue,3  
wed,4  
thu,5  
fri,6  
sat,7

Q.12.2    
★dfの1-3行を切り出してnew_dfとし、dfに行を追加する形でappendせよ。  
その際に、インデックスは初期化せよ。

Q.13.1    
★ dfのday_of_weekをone-hotエンコーディングしたデータフレームを表示せよ。